[env]
lib_deps = https://github.com/simondlevy/TinyEKF.git

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
build_unflags = -std=gnu++17
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_FREERTOS
    -std=gnu++23
monitor_speed = 115200

[env:native]
platform = native
test_framework = unity
build_flags =
    -std=c++23
    -Wall
    -Wextra
    -DUNITY_INCLUDE_DOUBLE
    -DUNITY_INCLUDE_FLOAT
    -I lib/mti_imu
    -I lib/septentrio_gnss
    -I lib/fusion
