#!/usr/bin/env python3
"""Generate include/tuning.h from tuning.toml.

Single source of truth: the EKF tuning the sim reads from tuning.toml is the
tuning the firmware compiles in. Runs as a PlatformIO `pre:` extra-script (it
regenerates on every pico build) or standalone via --output.

Stdlib only -- the pico build runs this under PlatformIO's Python, not the
sim's uv venv, so it must not import plrs_sim. euler_to_quaternion below is a
port of sim/plrs_sim/attitude.py; test_tuning_codegen guards that the two stay
in agreement.
"""

from __future__ import annotations

import argparse
import math
import tomllib
from pathlib import Path

Quat = tuple[float, float, float, float]  # (w, x, y, z)


def _repo_root() -> Path:
    """Repo root, whether run standalone or as a PlatformIO extra-script.

    PlatformIO execs this file without a __file__; it exports the SCons `env`,
    whose PROJECT_DIR is the repo root.
    """
    try:
        return Path(__file__).resolve().parents[1]
    except NameError:
        return Path(env["PROJECT_DIR"])  # noqa: F821 -- exported by PlatformIO


def _multiply(a: Quat, b: Quat) -> Quat:
    aw, ax, ay, az = a
    bw, bx, by, bz = b
    return (
        aw * bw - ax * bx - ay * by - az * bz,
        aw * bx + ax * bw + ay * bz - az * by,
        aw * by - ax * bz + ay * bw + az * bx,
        aw * bz + ax * by - ay * bx + az * bw,
    )


def _axis_angle(axis: tuple[float, float, float], angle_rad: float) -> Quat:
    half = 0.5 * angle_rad
    s = math.sin(half)
    return (math.cos(half), axis[0] * s, axis[1] * s, axis[2] * s)


def euler_to_quaternion(roll_deg: float, pitch_deg: float, yaw_deg: float) -> Quat:
    """ZYX intrinsic angles to a quaternion: Rz(yaw) * Ry(pitch) * Rx(roll)."""
    d2r = math.pi / 180.0
    qx = _axis_angle((1.0, 0.0, 0.0), roll_deg * d2r)
    qy = _axis_angle((0.0, 1.0, 0.0), pitch_deg * d2r)
    qz = _axis_angle((0.0, 0.0, 1.0), yaw_deg * d2r)
    return _multiply(_multiply(qz, qy), qx)


def _lit(x: float) -> str:
    """Format a number as a round-trip-safe C++ float literal.

    repr() of a float always carries a '.' or exponent, so the 'f' suffix is
    always a valid float literal (never the invalid integer form "1000f").
    """
    return f"{repr(float(x))}f"


def render(tuning: dict) -> str:
    proc = tuning["process_noise"]
    init = tuning["initial_covariance"]
    mti = tuning["mti_noise"]
    gnss = tuning["gnss"]
    mount = tuning.get("imu_mount", {})
    qw, qx, qy, qz = euler_to_quaternion(
        mount.get("mount_roll_deg", 0.0),
        mount.get("mount_pitch_deg", 0.0),
        mount.get("mount_yaw_deg", 0.0),
    )
    return f"""\
// Generated by scripts/gen_tuning.py from tuning.toml. Do not edit.
//
// EKF tuning and GNSS calibration compiled into the firmware. Edit tuning.toml
// and rebuild; the pico env regenerates this header on every build.

#pragma once

#include "ekf_filter.h"
#include "gnss_bridge.h"

namespace tuning {{

inline constexpr fusion::TinyEkfFilter::Config kFilterConfig {{
    .q_heading_deg2 = {_lit(proc["heading_deg2"])},
    .q_roll_deg2 = {_lit(proc["roll_deg2"])},
    .q_pitch_deg2 = {_lit(proc["pitch_deg2"])},
    .q_bias_deg2_s2 = {_lit(proc["gyro_bias_deg2_s2"])},
    .p0_heading_deg2 = {_lit(init["heading_deg2"])},
    .p0_roll_deg2 = {_lit(init["roll_deg2"])},
    .p0_pitch_deg2 = {_lit(init["pitch_deg2"])},
    .p0_bias_deg2_s2 = {_lit(init["gyro_bias_deg2_s2"])},
    .mti_roll_variance_deg2 = {_lit(mti["roll_deg2"])},
    .mti_pitch_variance_deg2 = {_lit(mti["pitch_deg2"])},
    .mount = {{.boat_to_imu = fusion::UnitQuaternion::from_unit_unchecked(
                  {{{_lit(qw)}, {_lit(qx)}, {_lit(qy)}, {_lit(qz)}}})}},
}};

inline constexpr fusion::GnssAttitudeMount kGnssMount {{
    .baseline_offset_deg = {_lit(gnss["baseline_offset_deg"])},
    .fallback_heading_variance_deg2 = {_lit(gnss["fallback_heading_variance_deg2"])},
}};

}} // namespace tuning
"""


def generate(tuning_path: Path | None = None, output_path: Path | None = None) -> str:
    root = _repo_root()
    tuning_path = Path(tuning_path) if tuning_path else root / "tuning.toml"
    output_path = Path(output_path) if output_path else root / "include" / "tuning.h"
    with tuning_path.open("rb") as f:
        tuning = tomllib.load(f)
    text = render(tuning)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(text)
    return text


try:
    Import("env")  # noqa: F821 -- injected only when run as a PlatformIO extra-script
except NameError:
    pass
else:
    generate()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-t", "--tuning", type=Path)
    parser.add_argument("-o", "--output", type=Path)
    args = parser.parse_args()
    generate(args.tuning, args.output)
